version: '3.8'

services:
  # 1. The Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recruitment_db
    ports:
      - "5432:5432" # Maps Docker port 5432 to your Laptop port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Saves data so it doesn't vanish on restart

  # 2. Auth Service
  auth-service:
    build: ./auth-service # Looks for Dockerfile in this folder
    ports:
      - "8081:8080"
    environment:
      # Note: We use the service name 'postgres' as the hostname
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/recruitment_db?currentSchema=auth
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

  # 3. Recruitment Service
  recruitment-service:
    build: ./recruitment-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/recruitment_db?currentSchema=core
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

  # 4. API Gateway (The Entry Point)
  gateway:
    build: ./api-gateway
    ports:
      - "8080:8080" # You only need to talk to THIS port
    depends_on:
      - auth-service
      - recruitment-service

volumes:
  postgres_data: