version: '3.8'

services:
  # 1. The Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Auth Service
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8080"
    environment:
      # Connect to the 'auth' schema in Postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=auth
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres

  # 3. Recruitment Service
  recruitment-service:
    build: ./recruitment-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=core
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres

  # 4. API Gateway
  gateway:
    build: ./api-gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - recruitment-service

volumes:
  postgres_data: