services:
  auth-db:
    image: postgres:15
    container_name: iv1201_auth_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${AUTH_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./auth-service/src/main/resources/auth-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: always

  recruitment-db:
    image: postgres:15
    container_name: iv1201_recruitment_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${RECRUIT_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./recruitment-service/src/main/resources/recruitment-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: always

  auth-service:
    build: ./auth-service
    depends_on:
      - auth-db
    environment:
      # We construct the URL dynamically using the variables
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${AUTH_DB_HOST}:${AUTH_DB_PORT}/${AUTH_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=${JWT_SECRET}
      - RECRUITER_SECRET_CODE=${RECRUITER_SECRET_CODE}
    networks:
      - app-network

  recruitment-service:
    build: ./recruitment-service
    depends_on:
      - recruitment-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${RECRUIT_DB_HOST}:${RECRUIT_DB_PORT}/${RECRUIT_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - app-network

  gateway:
    build: ./api-gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - recruitment-service
    networks:
      - app-network
    environment:
      APP_FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET: ${JWT_SECRET}

  frontend:
    build: ./frontend-service
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - ./frontend-service:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=${VITE_API_URL}
    command: sh -c "npm install && npm run dev"

networks:
  app-network:
    driver: bridge

volumes:
  auth_db_data:
  recruitment_db_data: